### ISSUE TITLE
Feature Request: Importing CSVs

### ISSUE THREAD

**Issue by AvMavs** [twwspes/OfflineBPLog#1]
First, thank you for this application! My Grandma suffers from hypertension so this app is pretty nifty for logging her data without having to hand it over to any third party!

If you don't mind, I have a small feature request: the ability to import CSVs would be cool so we that we can have the same list across multiple devices.

**Comment by twwspes** [comment]
Hey, thanks for your comment. I have been looking for setting up csv-import functionality long ago, but I didn't do so given the difficulty of dealing with format of csv and my personal time constraint.  

However, an issue has been raised here, and that means I can't hide away from this.

**Comment by AvMavs** [comment]
Oh, please take your time, it's just an enhancement per se. 

Thank you once again for this app!

**Comment by AvMavs** [comment]
Made a tool to convert the CSV to an Excel Spreadsheet which will make it easier for people to read: https://github.com/AvMavs/blood-pressure-spreadsheet

**Comment by AvMavs** [comment]
Thank you!
